language: php
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
script:
  - composer phpunit
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
matrix:
  fast_finish: true
